config/routes.rb
Rails.application.routes.draw do

  get "/favorites" => "favorites#index"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  get '/logout' => 'sessions#destroy'

  get "/signup" => "users#new"
  post "/users" => "users#create"

  get "comments/new/:id" => "comments#new", as: "new_comment"
  
  post "/comments" => "comments#create"

  get "/drinks/index" => "drinks#index"
  get "/drinks/adv" => "drinks#adv_search"
  post "/drinks/adv_result" => "drinks#adv_result"
  post "/drinks/result" => "drinks#result"

  get "/tools" => "home#tools"

  root 'home#index'
  resources :favorites

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
	has_and_belongs_to_many :comment
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	before_action :is_authenticated?

  def index
  	@favorites = Favorite.where("user_id" => @current_user.id)
    @comments = Comment.where("user_id" => @current_user.id)
    # render json: @comments
  end

 def show
    @favorite = Favorite.find params[:id]
    @comments = Comment.where("drink_id" => params[:id]).where("user_id" => @current_user.id)

    base_url = 'http://addb.absolutdrinks.com/drinks/' + @favorite['drink_id']
    response = RestClient.get base_url, {
      :params => {
        :apiKey => ENV['ABSOLUT_KEY'],
        :start => '0',
        :pageSize => '500'
      }
    }
    @drink = JSON.parse(response)['result']
    @video_link = nil
      if @drink.first['videos'].first['video']
        @video_id = @drink.first['videos'].first['video']
        @video_link = "http://www.youtube.com/embed/" + @video_id
        # render text: @video_link
      else 
      end

    @image_link = "http://assets.absolutdrinks.com/drinks/transparent-background-white/soft-shadow/300x400/" + @drink.first['id'] + ".png"
    # render text: @image_link
  end

  def create

    # to avoid adding the same drink more than once
    # posted = Favorite.find_or_create_by(drink_id: post_params[:drink_id], user_id: post_params[:user_id])
    # if posted.save
    # 	posted.description = "hello"
    #   posted.img = post_params[:img]
    # end

    Favorite.create post_params
    redirect_to favorites_path
  end

  def destroy
  	result = Favorite.destroy params[:id]
    respond_to do |format|
    format.html {redirect_to :favorites}
    format.json {render json: result}
	end
  end

  private

  def post_params
    if @current_user
      render text: "hello"
      # params.require(:favorites).permit(:drink_id, :description, :img)
    else
      redirect_to '/login'
    end
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/favorites/index.html.erb
        <div class="row">
                <div class="col-lg-12">
                    <hr>
                    <h1 class="text-center"><%= @current_user.name %>s' Favorites!</h1>
                    <hr>
                </div>
                <% @favorites.each do |fav| %>
                <div class="col-lg-12 text-center">
                    <h3> <%= link_to fav.img, fav %> </h3>
                    <p> <%= fav.description %></p>
                    <% @comments.each do |com| %>
                        <% if com.drink_id.to_s == fav.id.to_s %>
                            <p><%= com.content %></p>
                        <% end %>
                    <% end %>
                    <%= link_to 'Delete', fav, :class => 'js-delete-btn btn btn-danger' %>
                    <%= link_to 'Add Comment', new_comment_path(fav), :class => 'btn btn-warning add-comm-btn' %>      <hr>
                </div>
                <% end %>
            </div>
        </div>
  
   
    <p class="copy_tag">Copyright &copy; DRINKMATE</p>  

app/views/favorites/show.html.erb
<div class="row">
<div class="container">
    <h2><%= @drink.first['name'] %>
    <p><% if @video_link %>
        <a href="#" class="btn btn-default btn-sm" data-toggle="modal" data-target="#videoModal" data-theVideo="<%= @video_link %>">WATCH VIDEO</a>
        <% end %></h2>
    </p>
    <div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="videoModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body"> <h4>How to make <%= @drink.first['name'] %></h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <div>
                        <iframe width="100%" height="350" src="<%= @video_link %>"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <img alt="Picture of drink" src="<%= @image_link %>">

    <h4 class="details_title">Description</h4>
    <h4><%= @drink.first['descriptionPlain'] %></h4>
    <p>Taste(s) : 
        <% @drink.first['tastes'].each do |t| %>
        <%= t['text'] %> 
        <% end %>
    </p>

    <p>Occasion(s) : 
        <% @drink.first['occasions'].each do |t| %>
        <%= t['text'] %> 
        <% end %>
    </p>

    <p>Served in : <%= @drink.first['servedIn']['text'] %></p>

    <p>Skill level : <%= @drink.first['skill']['name'] %></p>
    
    <% if @drink.first['isAlcoholic'] == false %>
        <p> Non-alcoholic </p>
    <% elsif @drink.first['isAlcoholic'] == true %>
        <p> Alcoholic </p>
    <% end %>

    <% if @drink.first['isHot'] == false %>
        <p> Cold </p>
    <% elsif @drink.first['isHot'] == true %>
        <p> Hot </p>
    <% end %>

    <% if @drink.first['isCarbonated'] == false %>
        <p> Not carbonated </p>
    <% elsif @drink.first['isCarbonated'] == true %>
        <p> Carbonated </p>
    <% end %>

    <h4 class="details_title">Ingredients</h4>
    <ul>
        <% @drink.first['ingredients'].each do |i| %>
        <li><h4><%= i['textPlain'] %></h4></li>
        <% end %>
    </ul>

    <h4 class="details_title">Tools</h4>
    <ul>
        <% @drink.first['tools'].each do |i| %>
        <li><h4><%= i['text'] %></h4></li>
        <% end %>
    </ul>
    
    <% if @comments %>
    <h3>Comments</h3>
    <% end %>
    <% @comments.each do |comm| %>
    	<div id="deleteMe comment">
    		<h4> You: <%= comm.content %> </h4>
    	</div>
    <% end %>

<button onclick="goBack()">Go Back</button>
</div>
</div>